const $ = (selector) => document.querySelector(selector);
const canvas = $('#glCanvas');
const frame = $('#canvasFrame');
const placeholder = $('#placeholder');
const upload = $('#imageUpload');
const intensity = $('#intensity');
const tempo = $('#tempo');
const sizeSelect = $('#canvasSize');
const presetSelect = $('#screenPreset');
const rotationSelect = $('#rotation');
const selectionMode = $('#selectionMode');
const multiSelect = $('#multiSelect');
const selectionShape = $('#selectionShape');
const flipHorizontal = $('#flipHorizontal');
const flipVertical = $('#flipVertical');
const selectionBox = $('#selectionBox');
const formatSelect = $('#exportFormat');
const qualitySelect = $('#exportQuality');
const durationSelect = $('#exportDuration');
const fpsSelect = $('#exportFps');
const exportButton = $('#exportButton');
const exportNote = $('#exportNote');

const effectFamilies = [
  ['pan', 'Pan'], ['zoom', 'Zoom'], ['color', 'Color'], ['wave', 'Wave'], ['orbit', 'Orbit'],
  ['ripple', 'Ripple'], ['drift', 'Drift'], ['pulse', 'Pulse'], ['tilt', 'Tilt'], ['blur', 'Texture'],
];
const styleNames = ['Aurora', 'Breeze', 'Cinematic', 'Dawn', 'Ember', 'Float', 'Glow', 'Horizon', 'Ink', 'Jewel', 'Kinetic', 'Lunar', 'Mist', 'Nova', 'Opal', 'Prism', 'Quiet', 'Radiant', 'Solar', 'Velvet'];
const effects = effectFamilies.flatMap(([type, family]) => Array.from({ length: 100 }, (_, index) => { const style = styleNames[index % styleNames.length]; return { type, variant: index % 20, name: `${family} ${style} ${Math.floor(index / 20) + 1}`, subtitle: `${family.toLowerCase()} motion · variation ${index + 1}` }; }));


let effect = effects[0];
let playing = true;
let sourceImage = null;
let startTime = performance.now();
let pausedAt = 0;
let exportInProgress = false;
let selections = [[0.25, 0.25, 0.75, 0.75]];
let selectionEffects = [0];
let selectionDelays = [0];
let selectionShapes = [0];
let activeSelection = 0;
let drawingSelection = false;
let movingSelection = false;
let moveOrigin = null;
let selectionStart = null;

const effectGrid = $('#effectGrid');
function renderEffects(query = '') {
  const term = query.trim().toLowerCase();
  effectGrid.innerHTML = effects.map((item, index) => ({ item, index })).filter(({ item }) => !term || `${item.name} ${item.subtitle}`.toLowerCase().includes(term)).map(({ item, index }) => `<button class="effect ${effect === item ? 'selected' : ''}" data-index="${index}" role="radio" aria-checked="${effect === item}"><span class="effect-icon effect-${item.type}"></span><strong>${item.name}</strong><small>${item.subtitle}</small></button>`).join('') || '<p class="no-effects">No animations match your search.</p>';
}
renderEffects();
$('#effectSearch').addEventListener('input', (event) => renderEffects(event.target.value));

const gl = canvas.getContext('webgl', { premultipliedAlpha: false, preserveDrawingBuffer: false });
if (!gl) throw new Error('WebGL is required to render this animation.');
const vertexSource = `attribute vec2 p; varying vec2 uv; void main(){uv=(p+1.0)*.5;gl_Position=vec4(p,0.,1.);}`;
const fragmentSource = `precision highp float; varying vec2 uv; uniform sampler2D image; uniform float time,power,mode,variant,ratio,imageRatio,rotation,selectionActive,selectionCount,flipX,flipY;uniform vec4 selectionA,selectionB,selectionC,selectionD,selectionModes,selectionDelays,selectionShapes;
vec2 cover(vec2 c){float r=ratio/imageRatio;return r>1.?vec2((c.x-.5)/r+.5,c.y):vec2(c.x,(c.y-.5)*r+.5);}
vec2 rotate(vec2 p,float a){float s=sin(a),c=cos(a);return mat2(c,-s,s,c)*(p-.5)+.5;}
float inRect(vec2 p,vec4 r){return step(r.x,p.x)*step(r.y,p.y)*step(p.x,r.z)*step(p.y,r.w);}
float inShape(vec2 p,vec4 r,float shape){if(shape<.5)return inRect(p,r);vec2 q=(p-(r.xy+r.zw)*.5)/((r.zw-r.xy)*.5);if(shape<1.5)return step(dot(q,q),1.);return step(abs(q.x)+abs(q.y),1.);}
vec2 areaMotion(vec2 p,float m,float t,float power,vec4 r){if(m<.5)p.x+=sin(t*.7)*.05*power;else if(m<1.5){float z=1.-.12*power*(.5+.5*sin(t));p=(p-.5)*z+.5;}else if(m<2.5){p.x+=sin(p.y*16.+t*2.)*.03*power;}else if(m<3.5)p+=vec2(cos(t),sin(t*.8))*.025*power;else if(m<4.5)p+=(p-.5)*sin(length(p-.5)*28.-t*4.)*.035*power;else if(m<5.5)p+=vec2(sin(t*.8),cos(t*.6))*.025*power;else if(m<6.5){float z=1.-.1*power*(.5+.5*sin(t));p=(p-.5)*z+.5;}else if(m<8.5)p.x+=sin(p.y*34.+t*3.)*.04*power;else if(m<9.5){vec2 c=(r.xy+r.zw)*.5;float a=t*power*2.;float cs=cos(a),sn=sin(a);p=mat2(cs,-sn,sn,cs)*(p-c)+c;}else p.y+=fract(t*.45)*.16*power;return p;}
void main(){vec2 raw=uv;if(flipX>.5)raw.x=1.-raw.x;if(flipY>.5)raw.y=1.-raw.y;raw=rotate(raw,rotation);vec2 p=raw;float t=time;float v=variant;if(mode<.5){p.x+=sin(t*.7+v)*.045*power*(v==1.?-1.:1.);p.y+=cos(t*.45)*.012*power;}else if(mode<1.5){float z=1.-.12*power*(.5+.5*sin(t*.75+v));p=(p-.5)*z+.5;}else if(mode<2.5){ }else if(mode<3.5){p.x+=sin(p.y*(12.+v*4.)+t*2.)*.028*power;p.y+=sin(p.x*10.+t*1.5)*.02*power;}else if(mode<4.5){p+=vec2(cos(t),sin(t*.8))*.025*power;}else if(mode<5.5){p+=(p-.5)*sin(length(p-.5)*28.-t*4.)*.035*power;}else if(mode<6.5){p+=vec2(sin(t*.8),cos(t*.6))*.025*power;}else if(mode<7.5){float z=1.-.1*power*(.5+.5*sin(t*(1.+v*.5)));p=(p-.5)*z+.5;}else if(mode<8.5){p.x+=(p.y-.5)*sin(t)*.07*power;}float insideA=inShape(raw,selectionA,selectionShapes.x),insideB=inShape(raw,selectionB,selectionShapes.y),insideC=inShape(raw,selectionC,selectionShapes.z),insideD=inShape(raw,selectionD,selectionShapes.w);float inside=max(max(insideA,insideB),max(insideC,insideD));vec2 areaP=areaMotion(raw,selectionModes.x,t-selectionDelays.x,power,selectionA);if(insideB>.5)areaP=areaMotion(raw,selectionModes.y,t-selectionDelays.y,power,selectionB);if(insideC>.5)areaP=areaMotion(raw,selectionModes.z,t-selectionDelays.z,power,selectionC);if(insideD>.5)areaP=areaMotion(raw,selectionModes.w,t-selectionDelays.w,power,selectionD);p=mix(raw,areaP,mix(1.,inside,selectionActive));vec4 c=texture2D(image,cover(p));if(mode>1.5&&mode<2.5)c.rgb+=.14*power*vec3(sin(t+uv.y*4.+v),sin(t*1.3+2.),sin(t*.8+4.));if(mode>8.5&&mode<9.5)c.rgb=mix(c.rgb,vec3(dot(c.rgb,vec3(.299,.587,.114))),.22*power)+sin((uv.x+uv.y+t)*300.)*.025*power;gl_FragColor=c;}`;
function compileShader(type, source) { const shader = gl.createShader(type); gl.shaderSource(shader, source); gl.compileShader(shader); if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(shader)); return shader; }
const program = gl.createProgram(); gl.attachShader(program, compileShader(gl.VERTEX_SHADER, vertexSource)); gl.attachShader(program, compileShader(gl.FRAGMENT_SHADER, fragmentSource)); gl.linkProgram(program); gl.useProgram(program);
const buffer = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, buffer); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1,-1,1,-1,-1,1,1,1]), gl.STATIC_DRAW);
const position = gl.getAttribLocation(program, 'p'); gl.enableVertexAttribArray(position); gl.vertexAttribPointer(position, 2, gl.FLOAT, false, 0, 0);
const texture = gl.createTexture(); gl.bindTexture(gl.TEXTURE_2D, texture); [gl.TEXTURE_MIN_FILTER, gl.TEXTURE_MAG_FILTER].forEach((key) => gl.texParameteri(gl.TEXTURE_2D, key, gl.LINEAR)); [gl.TEXTURE_WRAP_S, gl.TEXTURE_WRAP_T].forEach((key) => gl.texParameteri(gl.TEXTURE_2D, key, gl.CLAMP_TO_EDGE));
const uniform = (name) => gl.getUniformLocation(program, name);
const modes = { pan: 0, zoom: 1, color: 2, wave: 3, orbit: 4, ripple: 5, drift: 6, pulse: 7, tilt: 8, blur: 9 };
const areaModeForEffect = (index) => modes[effects[index].type];
function selectedDimensions() { if (sizeSelect.value === 'original' && sourceImage) return [sourceImage.naturalWidth, sourceImage.naturalHeight]; return sizeSelect.value.split('x').map(Number); }
function resizeCanvas() { const [width, height] = selectedDimensions(); canvas.width = width; canvas.height = height; frame.style.aspectRatio = `${width} / ${height}`; gl.viewport(0, 0, width, height); $('#resolution').textContent = sourceImage ? `${width} × ${height} output` : `${width} × ${height} selected`; }
function elapsed(now) { return playing ? (now - startTime) / 1000 : pausedAt; }
function render(now) { requestAnimationFrame(render); if (!sourceImage) return; gl.uniform1f(uniform('time'), elapsed(now) * (+tempo.value / 8)); gl.uniform1f(uniform('power'), +intensity.value / 100); gl.uniform1f(uniform('mode'), modes[effect.type]); gl.uniform1f(uniform('variant'), effect.variant); gl.uniform1f(uniform('ratio'), canvas.width / canvas.height); gl.uniform1f(uniform('imageRatio'), sourceImage.naturalWidth / sourceImage.naturalHeight); gl.uniform1f(uniform('rotation'), Number(rotationSelect.value) * Math.PI / 180); gl.uniform1f(uniform('selectionActive'), selectionMode.checked ? 1 : 0); gl.uniform1f(uniform('selectionCount'), selections.length); gl.uniform1f(uniform('flipX'), flipHorizontal.checked ? 1 : 0); gl.uniform1f(uniform('flipY'), flipVertical.checked ? 1 : 0); ['selectionA','selectionB','selectionC','selectionD'].forEach((name, index) => gl.uniform4fv(uniform(name), selections[index] || [0.,0.,0.,0.])); gl.uniform4fv(uniform('selectionModes'), selectionEffects.map((index) => index >= 1000 ? index - 1000 : areaModeForEffect(index)).concat([0,0,0,0]).slice(0,4)); gl.uniform4fv(uniform('selectionDelays'), selectionDelays.concat([0,0,0,0]).slice(0,4)); gl.uniform4fv(uniform('selectionShapes'), selectionShapes.concat([0,0,0,0]).slice(0,4)); gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4); }
requestAnimationFrame(render); resizeCanvas();
function setExportNote(message, tone = '') { exportNote.textContent = message; exportNote.className = `export-note ${tone}`; }
const selectionBoxes = [selectionBox];
const areaEffects = ['Pan', 'Zoom', 'Wave', 'Orbit', 'Ripple', 'Drift', 'Pulse', 'Tilt', 'Water flow', 'Wheel spin', 'Road motion'];
const selectionManager = $('#selectionManager');
const areaEffectPicker = $('#areaEffectPicker');
function renderSelectionManager() { if (!selectionMode.checked) { selectionManager.innerHTML = ''; return; } selectionManager.innerHTML = `<p>Selected animation areas · ${selections.length}/4</p>${selections.map((_, index) => `<div class="area-row ${index === activeSelection ? 'active' : ''}"><button type="button" data-area="${index}">Area ${index + 1}</button><select data-effect="${index}">${areaEffects.map((name, effectIndex) => `<option value="${effectIndex}" ${(selectionEffects[index] >= 1000 ? selectionEffects[index] - 1000 : areaModeForEffect(selectionEffects[index])) === effectIndex ? 'selected' : ''}>${name}</option>`).join('')}</select><select data-delay="${index}">${[0,.4,.8,1.2].map((delay) => `<option value="${delay}" ${selectionDelays[index] === delay ? 'selected' : ''}>+${delay}s</option>`).join('')}</select><button type="button" data-delete="${index}" aria-label="Delete area ${index + 1}">×</button></div>`).join('')}`; }
function renderAreaEffectPicker(query = '') { const term = query.trim().toLowerCase(); const matches = effects.map((item, index) => ({ item, index })).filter(({ item }) => !term || `${item.name} ${item.subtitle}`.toLowerCase().includes(term)).slice(0, 40); areaEffectPicker.innerHTML = `<p>Area ${activeSelection + 1} animation <button type="button" data-close>×</button></p><input type="search" placeholder="Search 1,000 effects" value="${query}" data-area-search><div>${matches.map(({ item, index }) => `<button type="button" data-area-effect="${index}" class="${selectionEffects[activeSelection] === index ? 'selected' : ''}">${item.name}</button>`).join('') || '<small>No effects found</small>'}</div>`; areaEffectPicker.hidden = false; }
function setSelectionBoxes() { selections.forEach((selection, index) => { let box = selectionBoxes[index]; if (!box) { box = selectionBox.cloneNode(true); box.removeAttribute('id'); frame.append(box); selectionBoxes.push(box); } const [x1,y1,x2,y2] = selection; box.dataset.areaIndex = index; box.style.left = `${x1*100}%`; box.style.top = `${y1*100}%`; box.style.width = `${(x2-x1)*100}%`; box.style.height = `${(y2-y1)*100}%`; box.classList.toggle('visible', selectionMode.checked); box.classList.toggle('active', index === activeSelection); box.classList.toggle('shape-circle', selectionShapes[index] === 1); box.classList.toggle('shape-polygon', selectionShapes[index] === 2); }); selectionBoxes.slice(selections.length).forEach((box) => box.classList.remove('visible')); renderSelectionManager(); }
function previewPoint(event) { const box = frame.getBoundingClientRect(); return [Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),Math.max(0,Math.min(1,(event.clientY-box.top)/box.height))]; }
function selectionAt(point) { return selections.findIndex(([x1,y1,x2,y2]) => point[0] >= x1 && point[0] <= x2 && point[1] >= y1 && point[1] <= y2); }
function removeArea(index) { if (selections.length < 2) { selectionMode.checked = false; } else { selections.splice(index,1); selectionEffects.splice(index,1); selectionDelays.splice(index,1); selectionShapes.splice(index,1); activeSelection=Math.max(0,Math.min(activeSelection,selections.length-1)); } areaEffectPicker.hidden = true; setSelectionBoxes(); }
frame.addEventListener('pointerdown', (event) => { if (!selectionMode.checked || !sourceImage) return; const targetBox = event.target.closest('.selection-box'); const boxIndex = targetBox ? Number(targetBox.dataset.areaIndex) : -1; if (event.target.closest('.selection-delete')) { event.stopPropagation(); removeArea(boxIndex); return; } if (event.target.closest('.selection-fx')) { event.stopPropagation(); activeSelection = boxIndex; renderAreaEffectPicker(); return; } selectionStart = previewPoint(event); const hit = multiSelect.checked ? selectionAt(selectionStart) : -1; frame.setPointerCapture(event.pointerId); if (event.target.closest('.selection-handle')) { activeSelection = boxIndex; movingSelection = false; drawingSelection = false; moveOrigin = [...selections[boxIndex]]; targetBox.dataset.resizing = 'true'; return; } if (hit >= 0) { activeSelection = hit; movingSelection = true; moveOrigin = [...selections[hit]]; setSelectionBoxes(); return; } drawingSelection = true; if (!multiSelect.checked) { selections = [[...selectionStart, ...selectionStart]]; selectionEffects = [selectionEffects[0] || 0]; selectionDelays = [0]; selectionShapes = [selectionShape.value === 'circle' ? 1 : selectionShape.value === 'polygon' ? 2 : 0]; activeSelection = 0; } else if (selections.length < 4) { selections.push([...selectionStart, ...selectionStart]); selectionEffects.push(0); selectionDelays.push(0); selectionShapes.push(selectionShape.value === 'circle' ? 1 : selectionShape.value === 'polygon' ? 2 : 0); activeSelection = selections.length - 1; } else activeSelection = selections.length - 1; selections[activeSelection] = [...selectionStart, ...selectionStart]; setSelectionBoxes(); });
frame.addEventListener('pointermove', (event) => { const resizingBox = frame.querySelector('[data-resizing="true"]'); if (!drawingSelection && !movingSelection && !resizingBox) return; const [x,y] = previewPoint(event); if (resizingBox) { selections[activeSelection] = [moveOrigin[0],moveOrigin[1],Math.max(moveOrigin[0]+.03,x),Math.max(moveOrigin[1]+.03,y)]; } else if (movingSelection) { const dx=x-selectionStart[0],dy=y-selectionStart[1],width=moveOrigin[2]-moveOrigin[0],height=moveOrigin[3]-moveOrigin[1],left=Math.max(0,Math.min(1-width,moveOrigin[0]+dx)),top=Math.max(0,Math.min(1-height,moveOrigin[1]+dy)); selections[activeSelection]=[left,top,left+width,top+height]; } else selections[activeSelection] = [Math.min(selectionStart[0],x),Math.min(selectionStart[1],y),Math.max(selectionStart[0],x),Math.max(selectionStart[1],y)]; setSelectionBoxes(); });
frame.addEventListener('pointerup', () => { drawingSelection = false; movingSelection = false; frame.querySelectorAll('[data-resizing="true"]').forEach((box) => delete box.dataset.resizing); });
selectionManager.addEventListener('click', (event) => { const area = event.target.dataset.area; const remove = event.target.dataset.delete; if (area !== undefined) { activeSelection = Number(area); setSelectionBoxes(); } if (remove !== undefined && selections.length > 1) { selections.splice(Number(remove),1); selectionEffects.splice(Number(remove),1); selectionDelays.splice(Number(remove),1); selectionShapes.splice(Number(remove),1); activeSelection=Math.max(0,Math.min(activeSelection,selections.length-1)); setSelectionBoxes(); } });
selectionManager.addEventListener('change', (event) => { const effectIndex = event.target.dataset.effect; const delayIndex = event.target.dataset.delay; if (effectIndex !== undefined) selectionEffects[Number(effectIndex)] = Number(event.target.value) >= 8 ? 1000 + Number(event.target.value) : effects.findIndex((item) => modes[item.type] === Number(event.target.value)); if (delayIndex !== undefined) selectionDelays[Number(delayIndex)] = Number(event.target.value); setSelectionBoxes(); });
areaEffectPicker.addEventListener('input', (event) => { if (event.target.matches('[data-area-search]')) renderAreaEffectPicker(event.target.value); });
areaEffectPicker.addEventListener('click', (event) => { const index = event.target.dataset.areaEffect; if (index !== undefined) { selectionEffects[activeSelection] = Number(index); areaEffectPicker.hidden = true; setSelectionBoxes(); } if (event.target.dataset.close !== undefined) areaEffectPicker.hidden = true; });
selectionMode.addEventListener('change', () => { setSelectionBoxes(); setExportNote(selectionMode.checked ? 'Draw, select, move, or assign a different effect to each area.' : 'The full image will animate.', 'success'); });
$('#addSelection').addEventListener('click', () => { selectionMode.checked = true; multiSelect.checked = true; if (selections.length < 4) { selections.push([0.25, 0.25, 0.75, 0.75]); selectionEffects.push(0); } activeSelection = selections.length - 1; setSelectionBoxes(); setExportNote('Select an area card, then drag its box to move it or draw a new area.', 'success'); });
$('#staggerAreas').addEventListener('click', () => { selectionMode.checked = true; multiSelect.checked = true; selectionDelays = selections.map((_, index) => Math.min(index * .4, 1.2)); setSelectionBoxes(); setExportNote('Area motion is now staggered by 0.4 seconds.', 'success'); });
$('#clearSelection').addEventListener('click', () => { selections = [[0.25, 0.25, 0.75, 0.75]]; selectionEffects = [0]; selectionDelays = [0]; selectionShapes = [0]; activeSelection = 0; selectionMode.checked = false; setSelectionBoxes(); setExportNote('Selected animation areas cleared.', 'success'); });
sizeSelect.addEventListener('change', () => { presetSelect.value = 'custom'; resizeCanvas(); });
presetSelect.addEventListener('change', () => { const values = { youtube:'1920x1080',short:'1080x1920',instagram:'1080x1080',reel:'1080x1920',tiktok:'1080x1920',x:'1600x900' }; if (values[presetSelect.value]) sizeSelect.value = values[presetSelect.value]; resizeCanvas(); });
upload.addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { sourceImage = new Image(); sourceImage.onload = () => { gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,sourceImage); placeholder.classList.add('hidden'); exportButton.disabled = false; resizeCanvas(); startTime = performance.now(); setExportNote('Ready to render your selected size and quality.', 'success'); }; sourceImage.src = reader.result; }; reader.readAsDataURL(file); });
effectGrid.addEventListener('click', (event) => { const button = event.target.closest('.effect'); if (!button) return; effect = effects[Number(button.dataset.index)]; $('#effectTitle').textContent = effect.name; startTime = performance.now(); renderEffects($('#effectSearch').value); });
intensity.addEventListener('input', () => { $('#intensityValue').textContent = `${intensity.value}%`; }); tempo.addEventListener('input', () => { $('#tempoValue').textContent = `${(+tempo.value/10).toFixed(1)}×`; });
function togglePlayback() { const currentElapsed=elapsed(performance.now()); playing=!playing; if(!playing) pausedAt=currentElapsed; else startTime=performance.now()-pausedAt*1000; const button=$('#playButton'); button.classList.toggle('paused',!playing); button.innerHTML=`<span></span>${playing?'Pause':'Play'}`; button.setAttribute('aria-label',playing?'Pause animation':'Play animation'); }
$('#playButton').addEventListener('click',togglePlayback); document.addEventListener('keydown',(event)=>{if(event.code==='Space'&&event.target.tagName!=='INPUT'&&event.target.tagName!=='SELECT'){event.preventDefault();togglePlayback();}}); $('#resetButton').addEventListener('click',()=>{intensity.value=42;tempo.value=8;sizeSelect.value='1280x720';presetSelect.value='custom';rotationSelect.value='0';selectionMode.checked=false;multiSelect.checked=false;flipHorizontal.checked=false;flipVertical.checked=false;selections=[[0.25,0.25,0.75,0.75]];selectionEffects=[0];selectionDelays=[0];selectionShapes=[0];selectionBoxes.forEach((box)=>box.classList.remove('visible'));intensity.dispatchEvent(new Event('input'));tempo.dispatchEvent(new Event('input'));effect = effects[0]; $('#effectSearch').value = ''; renderEffects(); $('#effectTitle').textContent = effect.name; resizeCanvas();});
function recorderOptions() { const requested=formatSelect.value==='mp4'?['video/mp4;codecs=avc1','video/mp4']:['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm']; const mimeType=requested.find((type)=>MediaRecorder.isTypeSupported(type)); return {mimeType,videoBitsPerSecond:{standard:5_000_000,high:12_000_000,ultra:24_000_000}[qualitySelect.value]}; }
exportButton.addEventListener('click',()=>{if(!sourceImage||exportInProgress)return;if(!canvas.captureStream||!window.MediaRecorder){setExportNote('Video export is not supported in this browser.','error');return;}const options=recorderOptions();if(!options.mimeType){setExportNote(`${formatSelect.value.toUpperCase()} export is not supported here. Try WebM.`,'error');return;}exportInProgress=true;const seconds=Number(durationSelect.value),wasPlaying=playing;if(!playing)togglePlayback();exportButton.disabled=true;exportButton.textContent=`Rendering ${seconds}s video…`;setExportNote(`Recording ${selectedDimensions().join(' × ')} at ${qualitySelect.value} quality.`,'success');const stream=canvas.captureStream(Number(fpsSelect.value)),chunks=[],recorder=new MediaRecorder(stream,options);recorder.ondataavailable=(event)=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=()=>{const extension=options.mimeType.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type:options.mimeType}),link=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:`motion-canvas-${canvas.width}x${canvas.height}.${extension}`});link.click();URL.revokeObjectURL(link.href);stream.getTracks().forEach((track)=>track.stop());exportInProgress=false;exportButton.disabled=false;exportButton.innerHTML='<span>↓</span> Download animation';setExportNote('Your animation download is ready.','success');if(!wasPlaying)togglePlayback();};recorder.start(200);window.setTimeout(()=>recorder.stop(),seconds*1000);});
